name: test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.8
  # just_audio:
  # path_provider: ^2.1.4
  # dio: ^5.5.0+1
  # just_audio_cache: ^0.1.2
  # connectivity_plus: ^6.0.4
  # just_audio_background: ^0.0.1-beta.13
  # audio_service: ^0.18.15
  # speech_to_text: ^6.6.2
  # rate_my_app: ^2.2.0
  # connectivity_plus: ^6.0.5
  # path_provider: ^2.1.4
  # flutter_pdfview: ^1.3.2
  # pip_view: ^0.9.7
  # flutter_downloader: ^1.11.8
  # pdf_viewer_plugin: ^2.0.1
  # permission_handler: ^11.3.1
  # miniplayer: ^1.0.1
  # dio: ^5.6.0
  # webview_flutter: ^2.0.0
  # facebook_audience_network: ^1.0.1
  # flutter_speedtest: ^0.2.0


  icons_launcher: ^2.1.7
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  http: ^1.2.2
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  search_page: ^2.3.0
  assets_audio_player: ^3.1.1
  # firebase_core: ^3.3.0
  # firebase_remote_config: ^5.0.4
  # dio: ^5.7.0
  # path_provider: ^2.1.4
  # intl: ^0.19.0
  hexcolor: ^3.0.1
  youtube_explode_dart: ^2.2.1
  cached_network_image: ^3.3.1
  package_info_plus: ^8.0.2
  quick_actions: ^1.0.7
  provider: ^6.1.2
  flutter_markdown: ^0.7.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.3.0
  flutter_lints: ^4.0.0


icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/audiobooks.json
    - assets/app_icon.png
    - assets/splash.png
    - CHANGELOG.md
  #   - images/a_dot_ham.jpegother descriptors for the font. For

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

