name: test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  icons_launcher: ^2.1.7
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  http: ^1.2.2
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  search_page: ^2.3.0
  assets_audio_player: ^3.1.1
  firebase_core: ^3.3.0
  dio: ^5.7.0
  path_provider: ^2.1.4
  hexcolor: ^3.0.1
  youtube_explode_dart: ^2.2.1
  cached_network_image: ^3.3.1
  package_info_plus: ^8.0.2
  quick_actions: ^1.0.7
  provider: ^6.1.2
  flutter_markdown: ^0.7.3+1
  connectivity_plus: ^6.0.5
  miniplayer: ^1.0.1
  firebase_analytics: ^11.3.1
  flutter_email_sender: ^6.0.3
  feedback: ^3.1.0
  cloud_firestore: ^5.4.2
  google_fonts: ^6.2.1
  # flutter_animated_progress_bar: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.3.0
  flutter_lints: ^4.0.0


icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    # - assets/audiobooks.json
    - assets/app_icon.png
    - assets/splash.png
    - CHANGELOG.md
  #   - images/a_dot_ham.jpegother descriptors for the font. For

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

