name: bookify_audio
description: "Bookify Audio"

version: 1.0.1+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.4
  http: ^1.3.0
  youtube_explode_dart: ^2.3.6
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.1
  quick_actions: ^1.1.0
  assets_audio_player_plus: ^3.1.2
  provider: ^6.1.2
  search_page: ^2.3.0
  carousel_slider: ^5.0.0
  auto_size_text: ^3.0.0
  hexcolor: ^3.0.1
  flutter_markdown: ^0.7.6
  font_awesome_flutter: ^10.8.0
  connectivity_plus: ^6.1.2
  icons_launcher: ^3.0.0
  flutter_lints: ^5.0.0
  audioplayers: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/splash.png
    - CHANGELOG.md

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700