// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACUc9vr6hgIKPpFFO8Q1TbWq1eVWyx0po',
    appId: '1:1001101373726:web:c9394f809f4a8019d6990f',
    messagingSenderId: '1001101373726',
    projectId: 'notify-4b1e0',
    authDomain: 'notify-4b1e0.firebaseapp.com',
    storageBucket: 'notify-4b1e0.appspot.com',
    measurementId: 'G-Y83GKSK1BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFwZ-YOONtQFaTUr7sXg00qFYSnm7KUc',
    appId: '1:1001101373726:android:cd2fad557bdb0961d6990f',
    messagingSenderId: '1001101373726',
    projectId: 'notify-4b1e0',
    storageBucket: 'notify-4b1e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOXn55EQ8SqxZymAfyGP_0F-FVo1t4CEc',
    appId: '1:1001101373726:ios:b5595e23374a394fd6990f',
    messagingSenderId: '1001101373726',
    projectId: 'notify-4b1e0',
    storageBucket: 'notify-4b1e0.appspot.com',
    iosBundleId: 'com.bookify.audio',
  );
}
